# Generated by Django 4.1.8 on 2023-06-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evchargingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AddStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('station_name', models.CharField(max_length=255)),
                ('location_city', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('owner_name', models.CharField(max_length=255)),
                ('slots_number', models.IntegerField()),
                ('timing', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evchargingapp.user')),
            ],
        ),
    ]
