# Generated by Django 4.1.8 on 2023-06-01 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evchargingapp', '0002_evuser_addstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('add_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evchargingapp.addstation')),
                ('ev_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evchargingapp.evuser')),
            ],
        ),
    ]
