# Generated by Django 4.1.8 on 2023-06-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evchargingapp', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=255)),
                ('ev_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evchargingapp.evuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evchargingapp.user')),
            ],
        ),
    ]
