# Generated by Django 4.1.8 on 2023-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evchargingapp', '0004_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Yes', max_length=255),
        ),
    ]
