# Generated by Django 4.1.8 on 2023-06-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evchargingapp', '0005_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstation',
            name='password',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='addstation',
            name='user_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
