# Generated by Django 4.1.8 on 2023-07-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evchargingapp', '0009_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstation',
            name='type',
            field=models.CharField(default='station', max_length=255),
        ),
    ]
